FROM golang:1.21 AS builder

RUN apt-get update && apt-get install -y git

WORKDIR /go/src/github.com/barkyq/gnost-relay

RUN git clone https://github.com/barkyq/gnost-relay.git .

RUN go mod download

RUN go build -o /go/bin/gnost-relay
RUN ls /go/bin

FROM golang:1.21

WORKDIR /

COPY --from=builder /go/bin/gnost-relay /gnost-relay
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]