name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master   # Trigger the deployment when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_CLIENT_WEB_BASE_URL: "/nostr-ts/"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Dependencies
      run: pnpm install --force

    - name: Build packages
      run: pnpm run build

    - name: Build client-web
      run: |
        cd client-web
        pnpm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./client-web/dist
        publish_branch: gh-pages
        user_name: 'GitHub Actions'
        user_email: 'github-actions-bot@users.noreply.github.com'
